# Generated by Django 5.0.7 on 2025-03-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritioninfo',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
