# Generated by Django 5.0.7 on 2025-03-09 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_nutritioninfo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmicalculation',
            name='daily_calories_needed',
            field=models.FloatField(default=2000),
        ),
        migrations.AddField(
            model_name='bmicalculation',
            name='goal',
            field=models.CharField(choices=[('gain', 'Gain Weight'), ('lose', 'Lose Weight'), ('maintain', 'Maintain Weight')], default='maintain', max_length=20),
        ),
        migrations.AlterField(
            model_name='nutritioninfo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_items', to='nutrition.category'),
        ),
    ]
