# Generated by Django 5.0.7 on 2025-03-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_bmicalculation_daily_calories_needed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritioninfo',
            name='healthy',
            field=models.BooleanField(default=True),
        ),
    ]
